spring.application.name=gym
spring.datasource.url=jdbc:postgresql://localhost:5432/gym
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=sfsdfsd4564gs5d64g65sd4g6s4d6545445665156414